# Generated by Django 3.2 on 2024-02-03 04:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_time', models.DateTimeField(default=datetime.datetime.now)),
                ('leave_time', models.DateTimeField(null=True)),
                ('working_hours', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('overtime_hours', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('break_time', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('attendance', models.IntegerField(choices=[(1, '出勤'), (0, '未出勤')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
